### ISSUE TITLE
rzls shows error notification on each edit in a `cshtml` file

### ISSUE THREAD

**Issue by kmoschcau** [tris203/rzls.nvim#68]
When editing text in a `cshtml` file, I get this error notification on each change:

> rzls: -32004: Specified argument was out of the range of valid values. (Parameter 'character')

**Comment by tris203** [comment]
Probably related to #59

**Comment by tris203** [comment]
I think this may have been resolved by #60 
Can you update to latest of everything and try again?

**Comment by kmoschcau** [comment]
It seems to be gone now. I'm closing this.

**Comment by kmoschcau** [comment]
@tris203 This problem came back. Can I just reopen this or would you like another issue?

**Comment by tris203** [comment]
> @tris203 This problem came back. Can I just reopen this or would you like another issue?

New issue that references this one please

If you can give me a full stack trace too that would be great
